server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3308/video-service?serverTimezone=Asia/Seoul
    username: min
    password: qwe123!
  servlet:
    multipart:
      enabled: true
      location: src/main/resources/static
      max-request-size: 30MB
      max-file-size: 10MB


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org:
      springframework:
        security:
          web: trace
    zerock: debug


com :
  video :
    upload :
      path : src/main/resources/static