server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3308/videoService?serverTimezone=Asia/Seoul
    username: min
    password: qwe123!
  sql:
    init:
      encoding: UTF-8
      mode: never
      schema-locations:
        - classpath:category.sql
        - classpath:keword.sql
        - classpath:user.sql
  servlet:
    multipart:
      enabled: true
      location: src/main/resources/static
      max-request-size: 30MB
      max-file-size: 10MB


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org:
      springframework:
        security:
          web: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    service: debug

com :
  video :
    upload :
      path : src/main/resources/static


cloud:
  aws:
    s3:
      bucket: video.service.file
    credentials:
      access-key: AKIATEMIZ4J6HOHDLRPI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
