INSERT INTO keywordentity (keyword, categorySeq) VALUES ('게임', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('PlayStation(플레이스테이션)', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('Xbox(엑스박스)', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('Nintendo(닌텐도)', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('Steam(스팀)', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('배틀로얄', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('슈팅', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('격투', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('어드벤처', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('플랫폼', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('오픈 월드', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('캐릭터', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('레벨업', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('파티', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('퍼즐', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('탐험', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('서바이벌', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('보드게임', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('메이플스토리 ', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('던전앤파이터 ', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('리그오브레전드', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('로스트아크', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('피파온라인', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('오버워치', 1);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('발로란트', 1);

INSERT INTO keywordentity (keyword, categorySeq) VALUES ('음악',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('팝',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('힙합',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('R&B',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('재즈',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('클래식',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('댄스',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('일렉트로닉', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('컨트리',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('블루스',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('레게', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('퓨전', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('인디', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('기타',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('피아노',2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('베이스', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('드럼', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('바이올린', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('첼로', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('트럼펫', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('색소폰', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('플루트', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('하프', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('솔로', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('듀엣', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('앙상블', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('콘서트', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('오케스트라', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('재즈 임프로비제이션', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('합창', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('가사', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('멜로디', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('리듬', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('하모니', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('후크', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('브릿지', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('인트로', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('아웃트로', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('코러스', 2);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('인스트루멘탈', 2);

INSERT INTO keywordentity (keyword, categorySeq) VALUES ('요리', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('고기', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('양파', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('마늘', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('당근', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('감자', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('토마토', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('브로콜리', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('고추', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('식초', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('간장', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('볶음', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('튀김', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('끓이기', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('구이', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('삶기', 3);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('굽기', 3);

INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스포츠', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('농구', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('야구', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('테니스', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('골프', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('수영', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('배드민턴', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('배구', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('하키', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스케이팅', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스노보드', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스키', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('육상', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('마라톤', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('볼링', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('사격', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('복싱', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('레슬링', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('요가', 4);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('필라테스', 4);


INSERT INTO keywordentity (keyword, categorySeq) VALUES ('공부', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('학문', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('학습', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('교육', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('독서', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('강의', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('수업', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('과제', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('시험', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('연구', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('프로젝트', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('학습 방법', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('전공', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('학교', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('대학', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('학생', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('교사', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('교육 기관', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('온라인 학습', 5);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('자기 계발', 5);

INSERT INTO keywordentity (keyword, categorySeq) VALUES ('감독', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('배우', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('장르', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스릴러', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('액션', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('코미디', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('드라마', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('공상과학', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('로맨스', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('판타지', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('애니메이션', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('뮤지컬', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('범죄', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('호러', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('가족 영화', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('역사', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('전쟁', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('스포츠', 6);
INSERT INTO keywordentity (keyword, categorySeq) VALUES ('어드벤처', 6);
